name: repcc_android
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  multicast_dns: ^0.3.2+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Icons/

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: Fonts/static/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: Fonts/static/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: Fonts/static/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: Fonts/static/JetBrainsMono-SemiBold.ttf
          weight: 600